###服务启动端口号
server:
  port: 80
  
###服务名称(服务注册到eureka名称)  
spring:
  application:
    name: app-mayikt-zuul
  redis:
    host: 47.106.190.68
    port: 6379
    password: 729754701
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
    ###数据库相关连接
  datasource:
    username: root
    password: 729754701
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.190.68:3306/meite_gateway?useUnicode=true&characterEncoding=UTF-8
    
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://47.106.190.68:8100/eureka


### 配置网关反向代理    
zuul:
  routes:
    api-weixin:
      ### 以 /api-weixin/访问转发到会员服务
      path: /api-weixin/**
      serviceId: app-mayikt-weixin
    api-member:
      ### 以 /api-member/访问转发到订单服务
      path: /api-member/**
      serviceId: app-mayikt-member
    api-pay:
      ### 以 /api-pay/访问转发到支付服务
      path: /api-pay/**
      serviceId: app-mayikt-pay
    public-api-pay:
      ### 以 /api-pay/访问转发到支付服务
      path: /public/api-pay/**
      serviceId: app-mayikt-pay