server:
  port: 8050

#### 整合freemarker
spring:
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    template-loader-path:
    - classpath:/templates
  application:
    name: app-mayikt-portal-pay-web

###服务注册到eureka地址
eureka:
  client:
    service-url:
      #defaultZone: http://127.0.0.1:8100/eureka
      #defaultZone: http://192.168.128.129:8080/eureka
      defaultZone: http://47.106.190.68:8100/eureka

redis:
  hostname: 47.106.190.68
  port: 6379
  password: 123456

xxl-sso:
  excluded:
    paths: 
xxl:
  sso:
    server: http://xxlssoserver.com:8080/xxl-sso-server
    logout:
      path: /logout
    redis:
      address: redis://47.106.190.68:6379
      
logging.level.org.springframework.boot.autoconfigure: ERROR