###服务启动端口号
server:
  port: 8800

###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://47.106.190.68:8100/eureka
  
spring:
  application:
    ###服务名称(服务注册到eureka名称)
    name: app-mayikt-integral
#  zipkin:
#      base-url: http://127.0.0.1:9411/
#      ###全部采集
#  sleuth:
#     sampler:
#      probability: 1.0
  redis:
    host: 47.106.190.68
    port: 6379
    password: 729754701
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
###数据库相关连接      
  datasource:
    username: root
    password: 729754701
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.190.68:3306/meite_integral?useUnicode=true&characterEncoding=UTF-8
  rabbitmq:
  ####连接地址
    host: 127.0.0.1
   ####端口号   
    port: 5672
   ####账号 
    username: guest
   ####密码  
    password: guest
   ### 地址
    virtual-host: /admin-host
    listener:
      simple:
        retry:
          ####开启消费者（程序出现异常的情况下会）进行重试
          enabled: true
          ####最大重试次数
          max-attempts: 5
          ####重试间隔时间
          initial-interval: 1000
        ####开启手动ack  
        acknowledge-mode: manual 
        default-requeue-rejected: false

####打印MyBatias日志    
logging:
  level:
  ### 开发环境使用DEBUG 生产环境info或者error
   com.mayikt.integral.mapper: DEBUG