logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG

###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://47.106.190.68:8100/eureka
server:
  port: 9800


  
spring:
  application:
    name: app-mayikt-spike
  redis:
    host: 47.106.190.68
    password: 729754701
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  ###数据库相关连接
  datasource:
    username: root
    password: 729754701
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.190.68:3306/meite_spike?useUnicode=true&characterEncoding=utf-8

  ###rabbitmq相关连接
  rabbitmq:
    ####连接地址
    host: 127.0.0.1
    ####端口号
    port: 5672
    ####账号
    username: guest
    ####密码
    password: guest
    ### 地址
    virtual-host: /admin-host
    ###开启消息确认机制 confirms
    publisher-confirms: true
    publisher-returns: true