logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG

###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://47.106.190.68:8100/eureka
server:
  port: 9800


  
spring:
  application:
    name: app-mayikt-spike
  redis:
    host: 47.106.190.68
    password: 729754701
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
###数据库相关连接      
  datasource:
    username: root
    password: 729754701
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.190.68:3306/meite_spike?useUnicode=true&characterEncoding=utf-8

  