server:
  port: 8085
logging:
  config: classpath:logback-spring.xml
xxl:
  job:
    executor:
      logpath: /data/applogs/xxl-job/jobhandler
      appname: xxl-job-executor-pay
      port: 9998
      logretentiondays: -1
      ip:
    admin:
      addresses: http://127.0.0.1:8081/xxl-job-admin
    accessToken:
